server.port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?logger=com.mysql.cj.log.StandardLogger&profileSQL=true&useTimezone=true&serverTimezone=GMT%2B3
    username: root
    password: mySQLpass123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  servlet:
    context-path: /